### ISSUE TITLE
Links to examples pages are broken

### ISSUE THREAD

**Issue by KamiKillertO** [ember-a11y/a11y-demo-app#30]
It seems that links to the examples are broken on https://ember-a11y.github.io/a11y-demo-app/.
![ember-a11y github io_a11y-demo-app_](https://user-images.githubusercontent.com/9579729/81306646-0017e100-9080-11ea-9a0e-c85b9164df75.png)
The links are working as we can access the examples pages but if you take a look at the URL you will notice that there's a `#` in the middle. For example, this is the link to the `aria-role` page https://ember-a11y.github.io/a11y-demo-app/#/examples/aria-role.

Having a `#` in the URL make it impossible to navigate to anchors on a specific page. For example, in the `aria-role` page there are 4 links that are normally connected to 4 anchors on the page. But if you click on them you are redirected to the home page of the demo app.

I've checked an this problem does not exist in local. Maybe something happens during the build and change the links :thinking: 

--------------------------------------------------------------------
[Update]

Ok I think it's this [line](https://github.com/ember-a11y/a11y-demo-app/blob/master/config/environment.js#L47)

**Comment by rajasegar** [comment]
We have build error here
https://github.com/ember-a11y/a11y-demo-app/runs/677531805?check_suite_focus=true
@KamiKillertO Can you please check?

**Comment by KamiKillertO** [comment]
Yes

**Comment by KamiKillertO** [comment]
Ok, it's also failing on master before my the PR #31. The fail seems to be caused by a dependency :thinking:, I'll have to dig into the build process to find the root cause :sweat_smile:
